uniq_col, uniq_col_count, uniq_duplicates_col - updated option key for column from f to c sort_uniq_count - fixed options, validation

diff --git a/tsv_scripts/sort_uniq_count b/tsv_scripts/sort_uniq_count
--- a/tsv_scripts/sort_uniq_count
+++ b/tsv_scripts/sort_uniq_count
@@ -22,7 +22,7 @@ Then re-sorts the output numerically by the count
 
 Syntax of $command_name:
 
-[ LINES ] | $command_name [ -s [ l | c | count | line ] ]  [ -o [ a | n | alpha | numeric | number ] ] [ -r ]
+[ LINES ] | $command_name [ -s [ l | c | count | line ] ]  [ -o [ a | alpha | n | numeric | number ] ] [ -r ]
 
 OPTIONAL OPTIONS:
 -s sortby     specify whether to sort by count of lines (default) or line text
@@ -36,6 +36,8 @@ OPTIONAL OPTIONS:
 
 # set default sort by to count of lines
 sortby="count";
+ordertype="alpha";
+
 # read command options
 while getopts "rs:o:h?" getopts_option
 do
@@ -51,8 +53,14 @@ shift $((OPTIND - 1));
 
 # validate options
 
+# option -s must be one of c count l line
 if [ "$( echo "$sortby" | egrep "^(c|count|l|line)$")" == "" ]; then 
-  echo "Option -s must be one of: c count l line;$help_usage" 1>&2 && exit 0;
+  echo "$command_name: ERROR: Option -s must be one of: c count l line;$help_usage" 1>&2 && exit 0;
+fi;
+
+# option -o must be one of a n alpha numeric number
+if  [ "$( echo "$sortby" | egrep "^(l|line)$")" != "" ] && [ "$( echo "$ordertype" | egrep "^(a|n|alpha|numeric|number)$")" == "" ]; then 
+  echo "$command_name: ERROR: Option -o must be one of: a alpha n numeric number;$help_usage" 1>&2 && exit 0;
 fi;
 
 # normalise sortby to full word
@@ -63,6 +71,7 @@ fi;
 
 # normalise ordertype to full word
 [ "$ordertype" = "n" ] && ordertype="numeric";
+[ "$ordertype" = "number" ] && ordertype="numeric";
 
 if [ "$reverse" -eq 0 ]; then
   # output order is not reversed
